### PR TITLE
Refactor/serialization

### PR DESCRIPTION
**Pull request by maximveksler**

### CODE REVIEW

**Comment by maximveksler** [comment]
@ZacharyWhitley thanks for the feedback and Merge.

What are "sparql results format types", I'm not sure I understand what you mean.

Example might be helpful.

**Comment by ZacharyWhitley** [comment]
https://www.w3.org/TR/sparql11-results-json/

mime-type: application/sparql-results+json

https://www.w3.org/TR/rdf-sparql-XMLres/

mime-type: application/sparql-results+xml

**Comment by maximveksler** [comment]
Interesting. I needed the previous because I was figuring out which formats GraphDB (Ontotext) can provide me (using the wrapper https://github.com/RDFLib/sparqlwrapper/blob/master/SPARQLWrapper/Wrapper.py#L770)

Where would the sparql mime types of the input come into play?

**Comment by ZacharyWhitley** [comment]
I was thinking under the "serialization" section. It's not a serialization of rdf but of sparql query results.

**Pull request merged**
