### PR TITLE
Add Perfect Memory to the list of companies

### PR DESCRIPTION
**Pull request by sroucheray**

### CODE REVIEW

**Comment by sroucheray** [comment]
Change category

**Comment by sroucheray** [comment]
Is someone willing to merge this PR ?

**Comment by zacharywhitley** [comment]
I can do that. Derivo is fine but can you explain how perfect memory is using semantic web technologies. It is not immediately clear from the web page.

**Comment by sroucheray** [comment]
> I can do that. Derivo is fine but can you explain how perfect memory is using semantic web technologies. It is not immediately clear from the web page.

Sure ! Perfect Memory is a software editor whose platform operates in 4 phases. First we ingest and analyze our customers data with AI services (analysis of text, images, video ...). Then we enrich these data by detecting named entities and, thanks to semantic inference rules, we are able to link information which was not, a priori. We use a variety of data sources, those of our customers of course but also Linked Open Data and others. More technically we use a semantic database (GraphDB), a semantic bus, all our micro-services communicate with semantic messages (rdfs). We also use a wide variety of semantic tools to ontologically model the businesses of our clients.

**Comment by zacharywhitley** [comment]
Thank you. Everything sounds good and I'm looking forward to taking a
closer look at your products. Your PR has been merged.

**Comment by justin2004** [comment]
> a semantic bus, all our micro-services communicate with semantic messages (rdfs)

@sroucheray can you say some more about the semantic bus? do you just send triples through Kafka or RabbitMQ or something like that?

**Comment by sroucheray** [comment]
> > a semantic bus, all our micro-services communicate with semantic messages (rdfs)
> 
> @sroucheray can you say some more about the semantic bus? do you just send triples through Kafka or RabbitMQ or something like that?

Yes, RabbitMQ is one of the tools we use internally for the transfer of semantic graphs. We also use API type micro-services.

**Comment by zacharywhitley** [comment]
How do you handle blank nodes?

**Pull request merged**
