### PR TITLE
Add Weaviate

### PR DESCRIPTION
**Pull request by bobvanluijt**
Added Weaviate to the overview

### CODE REVIEW

**Comment by bobvanluijt** [comment]
Friendly nudge :)

**Comment by zacharywhitley** [comment]
Thanks. I don't recall seeing an email for the original PR. Just one request. Can you remove the links to the videos? I'm sure they're interesting but adding additional links clutters the list and makes it impossible to draw the line especially with when companies request multiple links to docs, marketing material, blog posts, etc.

**Comment by bobvanluijt** [comment]
thanks, @zacharywhitley (tagging you in the hope it comes through 😄)

I've removed the videos.

**Comment by zacharywhitley** [comment]
I'm sorry but I'm going to have to decline this PR in its entirety. Your product is  interesting, although I find the licensing odd. You appear to have made the source available but it's proprietary. You only make copying available with permission for "development purposes". Are you expecting people to pull your code, make improvements and push them back to you so you can incorporate it into your proprietary product but get them to assign their copyright over to you before they do? 

That aside there is nothing in your product that uses semantic web technologies as this list is clearly about. There are some entries that occasionally stray from core semantic web technologies but they will still incorporate some aspects of semantic web technologies as embodied by the W3C recommendations. Your product closely resembles DGraph which, as you'll notice, is not included in this list which I could argue for since they do load RDF data. If your product does use semantic web technologies I would be happy to have you point them out and include them in this list, if not you may find a better fit in one of the many knowledge graph, or graph database awesome lists.

I also find it questionable the creation of a new heading with a singular entry of your own product as well as the numerous links to ancillary information on your product. 

Good luck with your product. I will be interested in seeing how it matures.

**Comment by bobvanluijt** [comment]
Hi @zacharywhitley, 

Thanks for your detailed response. Some responses to your remarks;

> You only make copying available with permission for "development purposes".

This has to do with [this article](https://www.nytimes.com/2019/12/15/technology/amazon-aws-cloud-competition.html). We wanted to allow people to use the software like any other OSS project (hence BSD-3), but avoid what the article states. If you have suggestions, I would love to hear them.

> Your product closely resembles DGraph which, as you'll notice, is not included in this list which I could argue for since they do load RDF data.

That's a fair point, although I would argue we solve a different problem (the build-in vectorization model) I appreciate the point.

> Good luck with your product. I will be interested in seeing how it matures.

Thanks, appreciated.

**Pull request closed without merging**
