### PR TITLE
add validating RDF data book

### PR DESCRIPTION
**Pull request by jimkont**

### CODE REVIEW

**Comment by ZacharyWhitley** [comment]
Thanks. I'll have to check out the book.

**Comment by maximveksler** [comment]
@jimkont thanks for the book reference, as a result I was able to learn about ShEx #64.

I appreciate the contribution.

**Comment by jimkont** [comment]
nice :) thanks  :+1: 

[we will create a more detailed ShEx related PR](https://gitter.im/shapeExpressions/Lobby?at=5c1c9c4dab910e7d3aad840e) but good that you added the spec

**Comment by maximveksler** [comment]
that would be great 👍 please do.

**Pull request merged**
